
################################
# top level directories
# only these would need to be changed if you have the same child directory structure
envdir: /mnt/isilon/cbmi/variome/rathik/tools/miniconda3/envs/pdx-subtract-env
rootdir: /mnt/isilon/maris_lab/target_nbl_ngs/PPTC-PDX-genomics/mouse_subtraction_pipeline
mytmpdir: /mnt/isilon/maris_lab/target_nbl_ngs/PPTC-PDX-genomics/mouse_subtraction_pipeline/tmpdir
################################

samples: $rootdir/rna-hybrid/metadata/samples.txt
binaries:
  java: /usr/bin/java
  perl: /usr/bin/perl
  ruby: /usr/bin/ruby
  bzip2: /usr/bin/bzip2
tools:
  star: $envdir/bin/STAR
  starfusion: $envdir/bin/STAR-Fusion
  bwa: $envdir/bin/bwa
  samtools: $envdir/bin/samtools
  sambamba: $envdir/bin/sambamba
  picard: $envdir/share/picard-2.18.14-0
  cufflinks: $envdir/bin/cufflinks
  rnaseqQC: $envdir/share/rna-seqc-1.1.8-0/RNA-SeQC_v1.1.8.jar
  alignstats: $envdir/bin/alignstats
  soapfuse: $rootdir/scripts/SOAPfuse-v1.26
  callhtseq: $rootdir/scripts/Htseq/call_htseq_v2.sh
  defuse: $rootdir/scripts/Defuse/run-defuse.sh
  ERCCPlot: $rootdir/scripts/ERCCQC_1.0/ERCCPlot.jar
  limsData: $rootdir/scripts/ERCCQC_1.0/RnaSeqLimsData.pl
  pindel: $rootdir/scripts/pindel_itd_stuff/pindel_0.2.5b5_tdonly
data:
  bed:
    hg19_bed: $rootdir/data/ref/mm10_hg19/hg19.bed
    mm10_bed: $rootdir/data/ref/mm10_hg19/mm10.bed
    vcrome_bed: $rootdir/data/capture_designs/HG19_vcrome2.1.bed
  ref:
    ERCCConc: $rootdir/data/ERCC92/ERCC_conc.tsv
    transcripts: $rootdir/data/ref/transcripts/protein_coding_canonical.T_chr.fa
    hg19_fasta: $rootdir/data/ref/hg19/hg19.fa.fai
    mm10_fasta: $rootdir/data/ref/mm10/mm10.fa.fai
    genomefile: $rootdir/data/ref/hg19_genome/Homo_sapiens.GRCh37.71.hap.ERCC.sm.fa
    genomedir: $rootdir/data/star_genomes/hg19_genome/
    genomedir_hybrid: $rootdir/data/star_genomes/mm10_hg19/
    genomefile_hybrid: $rootdir/data/ref/mm10_hg19/hg19_mm10.fa
    hg19_mm10_fasta: $rootdir/data/ref/mm10_hg19/hg19_mm10.fa.fai
  annotation:
    gtf_hybrid: $rootdir/data/gtf/hg19_mm10.gtf
    gtf: $rootdir/data/gtf/Homo_sapiens.GRCh37.71.hap.ERCC.gtf
    gtf_htseq: $rootdir/data/gtf/Homo_sapiens.GRCh37.71.hap.gene_name.gtf
dirs:
  logdir: $rootdir/rna-hybrid/results/logs/
  tmpdir: $mytmpdir
  fastqdir: $rootdir/data/fastq/
  outdirs:
    bamhybrid: $rootdir/rna-hybrid/results/bam/
    alignstatsdir: $rootdir/rna-hybrid/results/alignstats/
    realign: $rootdir/rna-hybrid/results/realign/
    realignstats: $rootdir/rna-hybrid/results/realignstats/
    htseqdir: $rootdir/rna-hybrid/results/htseq/
    bwaalign: $rootdir/rna-hybrid/results/bwa/
    bwaalignstats: $rootdir/rna-hybrid/results/bwaalignstats/
    defusedir: $rootdir/rna-hybrid/results/defuse/
    soapfusedir: $rootdir/rna-hybrid/results/soapfuse/
    rnaseqcdir: $rootdir/rna-hybrid/results/RNA-SeQC/
    pindeldir: $rootdir/rna-hybrid/results/pindel/
    cufflinksdir: $rootdir/rna-hybrid/results/cufflinks/

