
################################
# top level directories
# only these would need to be changed if you have the same child directory structure
envdir: /mnt/isilon/cbmi/variome/rathik/tools/miniconda3/envs/pdx-subtract-env
rootdir: /mnt/isilon/maris_lab/target_nbl_ngs/PPTC-PDX-genomics/mouse_subtraction_pipeline
mytmpdir: /mnt/isilon/maris_lab/target_nbl_ngs/PPTC-PDX-genomics/mouse_subtraction_pipeline/tmpdir
refdir: /mnt/isilon/cbmi/variome/reference
bindir: /mnt/isilon/cbmi/variome/bin
################################

samples: $rootdir/dna-pipeline/metadata/samples.txt
binaries:
  java: java
tools:
  bwa: $envdir/bin/bwa
  samtools: $envdir/bin/samtools
  sambamba: $envdir/bin/sambamba
  alignstats: $envdir/bin/alignstats
  bamutil: $envdir/bin/bam
  picard: $envdir/share/picard-2.18.14-0
  gatk_jar: $bindir/gatk/gatk-3.8.1
data:
  bed:
    hg19_bed: $rootdir/data/ref/mm10_hg19/hg19.bed
    mm10_bed: $rootdir/data/ref/mm10_hg19/mm10.bed
    vcrome_bed: $rootdir/data/capture_designs/HG19_vcrome2.1.bed
  ref:
    hg19_fasta: $rootdir/data/ref/hg19/hg19.fa.fai
    mm10_fasta: $rootdir/data/ref/mm10/mm10.fa.fai
    genomefile_hybrid: $rootdir/data/ref/mm10_hg19/hg19_mm10.fa
    genomefile_hybrid_index: $rootdir/data/ref/mm10_hg19/hg19_mm10.fa.fai
    gatk_ref: $rootdir/data/gatk_resource/
dirs:
  logdir: $rootdir/dna-pipeline/results/logs/
  tmpdir: $mytmpdir
  outdirs:
    dna_bamdir: $rootdir/dna-pipeline/results/bam/
    dna_fastqdir: $rootdir/dna-pipeline/results/fastq/
    realign: $rootdir/dna-pipeline/results/realign/
    realignstatsdir: $rootdir/dna-pipeline/results/realignstats/



